env:
  browser: true
  es2021: true

extends:
  # https://eslint.org/docs/latest/rules/
  - eslint:recommended
  # https://github.com/43081j/eslint-plugin-wc
  - plugin:wc/recommended
  # https://github.com/43081j/eslint-plugin-lit
  - plugin:lit/recommended
  # https://open-wc.org/docs/linting/eslint-plugin-lit-a11y/overview/
  - plugin:lit-a11y/recommended
  # https://github.com/prettier/eslint-config-prettier
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  # https://github.com/43081j/eslint-plugin-wc
  - wc
  # https://github.com/43081j/eslint-plugin-lit
  - lit
  # https://github.com/BenoitZugmeyer/eslint-plugin-html
  - html
  # https://open-wc.org/docs/linting/eslint-plugin-lit-a11y/overview/
  - lit-a11y

settings:
  wc:
    elementBaseClasses: [LitElement]

rules:
  # add additional rules from eslint-plugin-wc
  wc/no-constructor-params: error
  wc/no-typos: error
  wc/require-listener-teardown: error
